# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc28fe2930594c680f4768ee4d4b3b73da2de7025d4cd2eab7f78512dd369dbc15ba71377f6ff57d729df45b82f7a3642d728400b5a6bf965f01eb6f0c12f4e5

test:
  secret_key_base: 492d4486cdabb17e0741dccc953ff3937d6439f3f4eefa42d97c2c93b8c212b2069682c408a1c9444af5c453519fc240c54eacd9c10c99fa2ef88ddea61a211b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
